# Generated by Django 3.1 on 2020-08-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200808_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='menu',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='option',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='store',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='usertype',
            field=models.CharField(default='', max_length=50),
        ),
    ]
