# Generated by Django 3.1 on 2020-08-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200808_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='option',
            field=models.TextField(default='option'),
        ),
    ]
