# Generated by Django 3.1 on 2020-08-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200809_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(default='', max_length=50)),
                ('menu', models.CharField(default='', max_length=50)),
                ('option', models.TextField(default='option')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
