# Generated by Django 3.1 on 2020-08-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200809_0932'),
        ('main', '0008_user_price'),
    ]

    operations = [
    ]
