# Generated by Django 3.1 on 2020-08-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20200809_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(default=0, upload_to='store'),
            preserve_default=False,
        ),
    ]
